version: "2.0"
services:
  jenkins:
    image: juniper/nita-jenkins:21.7-1
    user: jenkins
    ports:
      - "8443:8443"
    volumes:
      - "/usr/bin/docker:/usr/bin/docker:ro"
      - "./certificates/jenkins_keystore.jks:/var/jenkins_home/jenkins_keystore.jks"
      - "/var/nita_project:/project:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - JENKINS_OPTS=--httpPort=8080 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/jenkins_keystore.jks --httpsKeyStorePassword=nita123
      - JENKINS_USER
      - JENKINS_PASS
    networks:
      - nita-network
    restart: always
volumes:
  jenkins_home:
networks:
  nita-network:
    external: true